[package]
name = "ctclient"
description = "Certificate Transparency Log client for monitoring and gossiping"
license = "MIT"
repository = "https://github.com/micromaomao/ctclient"
version = "0.1.0"
authors = ["Mao Wtm <m@maowtm.org>"]
edition = "2018"
documentation = "https://docs.rs/ctclient/0.1.0/ctclient/"

[[bin]]
name = "ctclient"
path = "src/bin.rs"

[lib]
name = "ctclient"
path = "src/lib.rs"

[dependencies]
reqwest = { version = "0.9.19" }
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
base64 = "0.10.1"
openssl = "0.10.24"
log = "0.4.7"

env_logger = "0.6.2"
